import '@picocss/pico';
import './globals.css';
import { Inter } from 'next/font/google';
import Navbar from './components/nav/Navbar';
import Hero from './components/hero/Hero';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Aquaman Pool Services',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en' data-theme='light'>
      <body className={inter.className}>
        <Hero />
        <Navbar />

        {children}
      </body>
    </html>
  );
}
