import '@picocss/pico';
import '../lib/pico-bootstrap-grid.min.css';
import './globals.css';
// import { Inter } from 'next/font/google';
import Navbar from '../components/nav/Navbar';
import Hero from '../components/hero/Hero';
import Contact from '../components/contact/Contact';
import Footer from '../components/footer/Footer';
import Overlay from '../components/overlay/Overlay';
import { useLocale } from 'next-intl';
import { notFound } from 'next/navigation';

// const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Aquaman Pool Services',
  description: 'Generated by create next app',
};

export default function RootLayout({ children, params }) {
  const locale = useLocale();

  // Show a 404 error if a user requests an unknown locale
  if (params.locale !== locale) {
    notFound();
  }

  return (
    <html lang={locale} data-theme='light'>
      <body /*className={inter.className}*/>
        <Hero />
        <Navbar />

        {children}

        <Overlay />
        <Contact />
        <Footer />
      </body>
    </html>
  );
}
