import '@picocss/pico';
import '../lib/pico-bootstrap-grid.min.css';
import './globals.css';
// import { Inter } from 'next/font/google';
import Navbar from '../components/nav/Navbar';
import Hero from '../components/hero/Hero';
import Contact from '../components/contact/Contact';
import Footer from '../components/footer/Footer';
import Overlay from '../components/overlay/Overlay';
import { useLocale, useTranslations } from 'next-intl';
import { notFound } from 'next/navigation';
import { Suspense } from 'react';
import Loading from './loading';

// const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Aquaman Pool Services',
  description: 'Generated by create next app',
};

export default function RootLayout({ children, params }) {
  const locale = useLocale();

  // Show a 404 error if a user requests an unknown locale
  if (params.locale !== locale) {
    notFound();
  }

  const t = useTranslations();
  const navItems = [
    t('Nav.contact'),
    t('Nav.services'),
    t('Nav.experience'),
    t('Nav.about'),
  ];

  return (
    <html lang={locale} data-theme='light'>
      <body /*className={inter.className}*/>
        <Suspense fallback={<Loading />}>
          <Hero />
          <Navbar
            locale={locale}
            nextLang={t('Nav.language')}
            navItems={navItems}
          />

          {children}

          <Overlay />
          <Contact locale={locale} />
          <Footer navItems={navItems} />
        </Suspense>
      </body>
    </html>
  );
}
